# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
-vmImage:'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/DevOps.TestApp.sln'
  project: '**/DevOps.TestApp.csproj'

steps: 
- task: NuGetToolInstaller@1
  name: 'NugetToolIntaller'
  displayName: 'Nuget tool Installer'

- task: NuGetCommand@2
  name: 'NugetRestore'
  displayName: 'Nuget Restore Packges'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Test'
  displayName: 'Run Test'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts'
  displayName: 'Publish build Artifacts'
  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'DevOpsTestProject'
        publishLocation: 'Container'